# Generated by Django 3.2.7 on 2021-09-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210922_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('toys', 'Toys'), ('eletronics', 'Eletronics'), ('fashion', 'Fashion'), ('home', 'Home')], default='varied', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
    ]
