# Generated by Django 3.2.7 on 2021-09-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('toys', 'Toys'), ('eletronics', 'Eletronics'), ('fashion', 'Fashion'), ('home', 'Home'), ('sports', 'Sports')], default='varied', max_length=64),
        ),
    ]
