# Generated by Django 3.2.7 on 2021-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210923_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=64),
        ),
    ]
