# Generated by Django 3.2.7 on 2021-09-23 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='number_of_bids',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='bids', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='listing',
            name='number_of_bids',
            field=models.IntegerField(default=0),
        ),
    ]
