# Generated by Django 3.2.7 on 2021-09-23 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210923_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bids', to='auctions.listing'),
        ),
    ]
