# Generated by Django 3.2.7 on 2021-09-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(default=models.FloatField()),
        ),
    ]
