# Generated by Django 3.2.7 on 2021-09-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_listing_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_price',
        ),
    ]
