# Generated by Django 3.2.7 on 2021-09-25 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
