# Generated by Django 3.2.7 on 2021-09-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_listing_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
    ]
