# Generated by Django 3.2.7 on 2021-09-26 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='listings_category', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
